apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-conversion
  labels:
    app: temperature-conversion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperature-conversion
  template:
    metadata:
      labels:
        app: temperature-conversion
    spec:
      containers:
        - name: temperature-conversion
          image: mganalistati/conv-temp-sec
          ports:
            - name: conv-temp-port
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: temperature-conversion
spec:
  selector:
    app: temperature-conversion
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: conv-temp-port
  type: LoadBalancer